### ISSUE TITLE
请问怎么使用 SDK 获取用户授权信息呢？

### ISSUE THREAD

**Issue by billLiao** [ExinOne/mixin-sdk-php#2]
请问怎么使用 SDK 获取用户授权信息呢？
没在文档中找到使用 code 换 access_token的方法和通过 access_token 获取用户资料的方法

**Comment by Kuri-su** [comment]
在 https://github.com/ExinOne/mixin-sdk-php/commit/023c312f04e4d04aab603a2954cba20e1b4be299 中已经添加上,抱歉

晚些时候会更新 Readme.md 中的文档

**Comment by Kuri-su** [comment]
文档也已经添加上了 

`network()->requestAccessToken($code)` 换取 access_token
然后使用  `network()->accessTokenGetInfo($accessToken)`  access_token 换取 用户资料

**Comment by billLiao** [comment]
感谢😋

**Comment by Kuri-su** [comment]
如果使用中碰到任何问题欢迎开 Issue 讨论 :)
