### ISSUE TITLE
怎么通过 sdk 获取授权登录的用户的资产信息呢？

### ISSUE THREAD

**Issue by billLiao** [ExinOne/mixin-sdk-php#3]
### 请问一下需要怎么获取授权用户的资产信息呢？
已经让用户授权，使用了MixinSDK::wallet()->readAssets() 这个函数，更换了配置中的  client_id  和 session_id 为授权用户的信息，但是提示 “Unauthorized, maybe invalid token.”

也试过修改 SDK，使用 /assets/:id ，也出现报错信息

**Comment by Kuri-su** [comment]
抱歉。。。上次少提供了一些方法和接口。。等下晚些时候会加上。。。

这里拿到 `access_token` 之后，应该将 `access_token` 放在 header 中，请求 
`/me`
`/friends`
`/assets`

这些接口

**Comment by Kuri-su** [comment]
在 https://github.com/ExinOne/mixin-sdk-php/commit/756cf22ac8443f71fd06981cfd829dc6fc71f371  (v1.0.6) 中已经添加上 

使用这个方法即可 `MixinSDK::network()->accessTokenGetAssets(string $access_token)` 获取到 asset 的信息

感谢回报 :laughing:

**Comment by billLiao** [comment]
那么 `access_token`存在有效期吗？还是说用户授权完以后可以存入数据库一直用，在官方文档中好像没有看到有说明

**Comment by Kuri-su** [comment]
大概一年的有效期

**Comment by billLiao** [comment]
感谢
