### ISSUE TITLE
fix: IDE 友好

### ISSUE THREAD

**Issue by Kuri-su** [ExinOne/mixin-sdk-php#5]
因为外部使用了_call 这种魔术方法, 导致 IDE 无法对 对象 的方法进行联想,建议在为 SDK 添加新的方法的时候, 更新一下函数签名到 https://github.com/ExinOne/mixin-sdk-php/blob/master/src/Container.php#L13-L81 , 方便 IDE 联想

@JokerLinly @Roachard

**Comment by Lorca-R** [comment]
PR Welcome 🎉🎉

**Comment by Kuri-su** [comment]
淦, 我就知道 :joy_cat: 
#FeatureRequest
